### ISSUE TITLE
`turbo prune` will remove pnpm `injectworkspacepackages` option from `pnpm-lock.yml`

### ISSUE THREAD

**Issue by anthonyshew** [vercel/turborepo#10584]
### Discussed in https://github.com/vercel/turborepo/discussions/10541

<div type='discussions-op-text'>

<sup>Originally posted by **YKDZ** June  3, 2025</sup>
### Summary

Hello everyone. When I worked with the pnpm `injectWorkspacePackages` option and `turbo prune --docker`, I found that the `settings.injectWorkspacePackages` option would be removed from the `pnpm-lock.yml` generated in the `out/` and `out/json/` etc, which would cause the `pnpm install --frozen-lockfile` command in `out/json/` throw error `ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "settings.injectWorkspacePackages" configuration doesn't match the value found in the lockfile`. I want to know if this is expected behavior or a bug?

### Additional information

Currently I am using script like this in my `Dockerfile` to avoid this behavior:
```Dockerfile
FROM base AS pruner
WORKDIR /repo

COPY . .

RUN turbo prune @cat/app --docker --use-gitignore=false

RUN sed -i '/^settings:/a \  injectWorkspacePackages: true' ./out/pnpm-lock.yaml \
    && sed -i '/^settings:/a \  injectWorkspacePackages: true' ./out/json/pnpm-lock.yaml
```

### Example

https://github.com/YKDZ/turbo-pnpm-injectWorkspacePackages</div>

**Comment by moderj** [comment]
it seems like turbo prune removes injected worspaces deps from the lockfile, so adding the setting is not enough, you also need to recover the removed deps

That's an error build I get after using the script specified here, out/json/pnpm-lock.yaml indeed does not have the injected workspace in it.
```js
227  ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for '@org/mongodb@file:packages/mongodb' in pnpm-lock.yaml
2.227 
2.227 This issue is probably caused by a badly resolved merge conflict.
2.227 To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
```

**Comment by emilio-martinez** [comment]
Duplicate of https://github.com/vercel/turborepo/issues/10544 (or the other way around)?

**Comment by LucasLundJensen** [comment]
@anthonyshew Why was this closed as `not planned`? It is intentional behaviour or a bug?

**Comment by anthonyshew** [comment]
It's a duplicate of [https://github.com/vercel/turborepo/issues/10544](https://github.com/vercel/turborepo/issues/10544).<br><br>(I had low connectivity when I closed and looks like my comment saying so never went through and I didn't realize, sorry about that!)

EDIT: Realizing now though that this one is the issue with more people on it. Re-opening this one and closing the #10544 instead.

**Comment by anthonyshew** [comment]
Should be fixed on 2.5.9-canary.8! Can folks on this issue try it out?

**Comment by moderj** [comment]
@anthonyshew Just tried to run 2.5.9-canary.8 and it still fails with a similar error.
```js
#14 1.313  WARN  Broken lockfile: no entry for '@org/mongodb@file:packages/mongodb' in pnpm-lock.yaml
#14 1.329  ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  The lockfile is broken! Resolution step will be performed to fix it.
#14 1.369 node_modules/.pnpm                       |  WARN  Cannot find resolution of @org/mongodb@file:packages/mongodb in lockfile
```

**Comment by anthonyshew** [comment]
@moderj Please share your lockfile, both the original lockfile and the lockfile emitted by the `prune` command. If you're unable to share it here due to privacy concerns, please email to anthony.shew@vercel.com and mention this issue number.

**Comment by moderj** [comment]
@anthonyshew Hey, it took me a long time, but I've managed to come up with a reproduction that demonstrates the issue.
I've created a repo and sent you an invite. I also dug into the turborepo code, and I think I know what causes the issue, so let me know if I can help in any way.

**Comment by moderj** [comment]
@anthonyshew I've updated to the latest 2.6.0 release and it's still the case

**Comment by moderj** [comment]
@anthonyshew can be closed imo, as this is resolved. I've created a different issue for my specific issue
