### ISSUE TITLE
Version 2.7.2: TUI not shown

### ISSUE THREAD

**Issue by mutewinter** [vercel/turborepo#11352]
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### Which canary version will you have in your reproduction?

2.7.2

### Environment information

```block
macOS 25 and PNPM 10.26.2.
```

### Expected behavior

TUI shows when not FULL TURBO.

### Actual behavior

TUI doesn't show.

### To Reproduce

I downgraded to 2.7.1 and this issue isn't happening. Seems to have some interaction with ` --output-logs errors-only`. 

### Additional context

I'm guessing https://github.com/vercel/turborepo/pull/11306 caused this.

**Comment by anthonyshew** [comment]
Hi, please provide a full reproduction. Thanks!

**Comment by tjsousa** [comment]
This also happens to me. macOS 26 and PNPM 10.24.0

**Comment by anthonyshew** [comment]
Back in-office, and taking a look at this, fix coming shortly.

**Comment by anthonyshew** [comment]
Should be fixed in [2.7.3](https://github.com/vercel/turborepo/releases/tag/v2.7.3)! Sorry about that.

**Comment by marcfrankel** [comment]
This is still not working for me. It seemed to appear out of nowhere that my setting for "ui": "tui" is being ignored.

**Comment by anthonyshew** [comment]
@marcfrankel Please provide a reproduction.

Given that there is no reproduction on this issue and I guess and checked until I found a bug that resembled what was described, I'm going to have leave this closed until I have something I can reproduce.

**Comment by mutewinter** [comment]
My issue was fixed by 2.7.3.
