### ISSUE TITLE
not detecting that a project is running on 3000

### ISSUE THREAD

**Issue by MariuzM** [vercel/turborepo#288]
### What version of Turborepo are you using?

1.0.11

### Describe the Bug

When i have a separate project running on port 3000 and then running turbo repo example projects `npm run dev` it does not detect that port 3000 is taken. Console still outputs for both example projects 3000 and 3001, so when i open http://localhost:3000 it open the previous project not related to turborepo 

### Expected Behavior

Next port should be used 3001 and 3002

### To Reproduce

npm run dev

**Comment by jaredpalmer** [comment]
Should be fixed in 1.0.14

**Comment by ivorpad** [comment]
@jaredpalmer Still happening in 1.0.29

Tries 3000, if in use tries 3001, if in use `exit code 1` and should be changing to 3002

```bash
$ turbo run dev --parallel
• Packages in scope: config, docs, tsconfig, ui, web
• Running dev in 5 packages
docs:dev: cache miss, executing 64f9a2565be42c12
web:dev: cache miss, executing 94b2c3c13578c78a
web:dev: $ next dev
docs:dev: $ next dev --port 3001
web:dev: warn  - Port 3000 is in use, trying 3001 instead.
web:dev: ready - started server on 0.0.0.0:3001, url: http://localhost:3001
docs:dev: Port 3001 is already in use.
docs:dev: error Command failed with exit code 1.
docs:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
docs:dev: Error: command finished with error: exit status 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
