### ISSUE TITLE
 ERROR  yarn.lock: yaml: line 9184: could not find expected ':'

### ISSUE THREAD

**Issue by NullVoxPopuli** [vercel/turborepo#394]
### What version of Turborepo are you using?

1.0.20-canary.1 and 1.0.19

### Describe the Bug

I cannot run _any_ command.

All commands give this error:
```
 ERROR  yarn.lock: yaml: line 9184: could not find expected ':'
```

### Expected Behavior

I can run commands

### To Reproduce

Here is the lockfile entry it's complaining about (it's due to yarn-resolutions being used to de-dupe the dependency).

(line 9184)
```
ember-cli-babel@6.11.0, ember-cli-babel@7.26.10, ember-cli-babel@7.26.6, ember-cli-babel@^6.0.0, ember-cli-babel@^6.0.0-beta.4, ember-cli-babel@^6.10.0, ember-cli-babel@^6.16.0, ember-cli-babel@^6.17.0, ember-cli-babel@^6.6.0, ember-cli-babel@^6.7.2, ember-cli-babel@^6.8.1, ember-cli-babel@^6.8.2, ember-cli-babel@^6.9.0, ember-cli-babel@^7.0.0, ember-cli-babel@^7.1.0, ember-cli-babel@^7.1.2, ember-cli-babel@^7.1.3, ember-cli-babel@^7.10.0, ember-cli-babel@^7.11.1, ember-cli-babel@^7.12.0, ember-cli-babel@^7.13.0, ember-cli-babel@^7.13.2, ember-cli-babel@^7.17.2, ember-cli-babel@^7.18.0, ember-cli-babel@^7.19.0, ember-cli-babel@^7.2.0, ember-cli-babel@^7.20.0, ember-cli-babel@^7.20.5, ember-cli-babel@^7.21.0, ember-cli-babel@^7.22.1, ember-cli-babel@^7.23.0, ember-cli-babel@^7.23.1, ember-cli-babel@^7.26.10, ember-cli-babel@^7.26.2, ember-cli-babel@^7.26.3, ember-cli-babel@^7.26.5, ember-cli-babel@^7.26.6, ember-cli-babel@^7.26.8, ember-cli-babel@^7.4.0, ember-cli-babel@^7.4.1, ember-cli-babel@^7.7.0, ember-cli-babel@^7.7.3:
```
note that there _is_ a colon at the end. So, idk if the parser is just giving up because the line is so long or what :shrug:

**Comment by NullVoxPopuli** [comment]
what's goofy is that I can edit this line to be _whatever_ I want, even something short, and I still get the error. Maybe a cache issue is at play?

**Comment by jaredpalmer** [comment]
what OS / arch are you using turbo with?

**Comment by NullVoxPopuli** [comment]
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

❯ uname -a
Linux ml-c02yt4etlvdr-ubuntu-vm 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

what's weird is that this error doesn't happen in my other monorepo I'm testing turborepo in.
https://github.com/NullVoxPopuli/limber/pull/377
(way smaller (~ 150 projects smaller))

**Comment by jaredpalmer** [comment]
can you DM me your lockfiles on Discord ? want to see if there is some sort of weird entry

**Comment by NullVoxPopuli** [comment]
I can't sorry -- too much information in there that references or hints at internal products.

I can provide the entries around the line with the error though, cause it's just OSS packages (if this helps? :shrug: )

<detail><summary>surrounding lockfile text</summary>

```yml
ember-cli-autoprefixer@2.0.0:
  version "2.0.0"
  resolved "<registry>/ember-cli-autoprefixer/-/ember-cli-autoprefixer-2.0.0.tgz#5c753aeb7ead9a954892cdf1f6f258abce01b907"
  integrity sha512-WVwfcwRoSjoR7NMfzsS4yWmAhs7FF5BfWzvdcyhvKl4wNzv4QSx9rjVV4dVcnY7pnj19OlSgLaXZ5Rt/P6u6dw==
  dependencies:
    broccoli-autoprefixer "^9.0.0"
    ember-cli-htmlbars "^5.0.0"

ember-cli-babel-plugin-helpers@1.1.1, ember-cli-babel-plugin-helpers@^1.0.0, ember-cli-babel-plugin-helpers@^1.1.0, ember-cli-babel-plugin-helpers@^1.1.1:
  version "1.1.1"
  resolved "<registry>/ember-cli-babel-plugin-helpers/-/ember-cli-babel-plugin-helpers-1.1.1.tgz#5016b80cdef37036c4282eef2d863e1d73576879"
  integrity sha512-sKvOiPNHr5F/60NLd7SFzMpYPte/nnGkq/tMIfXejfKHIhaiIkYFqX8Z9UFTKWLLn+V7NOaby6niNPZUdvKCRw==

ember-cli-babel@6.11.0, ember-cli-babel@7.26.10, ember-cli-babel@7.26.6, ember-cli-babel@^6.0.0, ember-cli-babel@^6.0.0-beta.4, ember-cli-babel@^6.10.0, ember-cli-babel@^6.16.0, ember-cli-babel@^6.17.0, ember-cli-babel@^6.6.0, ember-cli-babel@^6.7.2, ember-cli-babel@^6.8.1, ember-cli-babel@^6.8.2, ember-cli-babel@^6.9.0, ember-cli-babel@^7.0.0, ember-cli-babel@^7.1.0, ember-cli-babel@^7.1.2, ember-cli-babel@^7.1.3, ember-cli-babel@^7.10.0, ember-cli-babel@^7.11.1, ember-cli-babel@^7.12.0, ember-cli-babel@^7.13.0, ember-cli-babel@^7.13.2, ember-cli-babel@^7.17.2, ember-cli-babel@^7.18.0, ember-cli-babel@^7.19.0, ember-cli-babel@^7.2.0, ember-cli-babel@^7.20.0, ember-cli-babel@^7.20.5, ember-cli-babel@^7.21.0, ember-cli-babel@^7.22.1, ember-cli-babel@^7.23.0, ember-cli-babel@^7.23.1, ember-cli-babel@^7.26.10, ember-cli-babel@^7.26.2, ember-cli-babel@^7.26.3, ember-cli-babel@^7.26.5, ember-cli-babel@^7.26.6, ember-cli-babel@^7.26.8, ember-cli-babel@^7.4.0, ember-cli-babel@^7.4.1, ember-cli-babel@^7.7.0, ember-cli-babel@^7.7.3:
  version "7.26.10"
  resolved "<registry>/ember-cli-babel/-/ember-cli-babel-7.26.10.tgz#93565bef47b154ec0c1ceafacfd1474a01002ddc"
  integrity sha1-k1Zb70exVOwMHOr6z9FHSgEALdw=
  dependencies:
    "@babel/core" "^7.12.0"
    "@babel/helper-compilation-targets" "^7.12.0"
    "@babel/plugin-proposal-class-properties" "^7.16.5"
    "@babel/plugin-proposal-decorators" "^7.13.5"
    "@babel/plugin-proposal-private-methods" "^7.16.5"
    "@babel/plugin-proposal-private-property-in-object" "^7.16.5"
    "@babel/plugin-transform-modules-amd" "^7.13.0"
    "@babel/plugin-transform-runtime" "^7.13.9"
    "@babel/plugin-transform-typescript" "^7.13.0"
    "@babel/polyfill" "^7.11.5"
    "@babel/preset-env" "^7.16.5"
    "@babel/runtime" "7.12.18"
    amd-name-resolver "^1.3.1"
    babel-plugin-debug-macros "^0.3.4"
    babel-plugin-ember-data-packages-polyfill "^0.1.2"
    babel-plugin-ember-modules-api-polyfill "^3.5.0"
    babel-plugin-module-resolver "^3.2.0"
    broccoli-babel-transpiler "^7.8.0"
    broccoli-debug "^0.6.4"
    broccoli-funnel "^2.0.2"
    broccoli-source "^2.1.2"
    calculate-cache-key-for-tree "^2.0.0"
    clone "^2.1.2"
    ember-cli-babel-plugin-helpers "^1.1.1"
    ember-cli-version-checker "^4.1.0"
    ensure-posix-path "^1.0.2"
    fixturify-project "^1.10.0"
    resolve-package-path "^3.1.0"
    rimraf "^3.0.1"
    semver "^5.5.0"

ember-cli-blueprint-test-helpers@0.19.2:
  version "0.19.2"
  resolved "<registry>/ember-cli-blueprint-test-helpers/-/ember-cli-blueprint-test-helpers-0.19.2.tgz#9e563cd81ab39931253ced0982c5d02475895401"
  integrity sha512-otCKdGcNFK0+MkQo+LLjYbRD9EerApH6Z/odvvlL1hxrN+owHMV5E+jI2rbtdvNEH0/6w5ZqjH4kS232fvtCxQ==
  dependencies:
    chai "^4.1.0"
    chai-as-promised "^7.0.0"
    chai-files "^1.0.0"
    debug "^4.1.0"
    ember-cli-internal-test-helpers "^0.9.1"
    fs-extra "^7.0.0"
    testdouble "^3.2.6"
    tmp-sync "^1.0.0"

```

</detail>

**Comment by viniciuspjardim** [comment]
I have the same error in a simple example:

https://gitlab.com/viniciuspjardim/turborepo-test/-/jobs/1919352767

You can see the error in the line 110:

```
ERROR  yarn.lock: yaml: line 6: mapping values are not allowed in this context
```

The project source code is here:
https://gitlab.com/viniciuspjardim/turborepo-test

I'm in the branch `add-gitlab-ci` commit `48050f9dbed0e978c1752cfbc562bcaca66fec33` now.

In my local machine `yarn build` runs fine.

**Comment by weyert** [comment]
Thanks for the repro's. I will have a look

**Comment by viniciuspjardim** [comment]
Update:

My `yarn.lock` was with the `EOL` char `\r\n`. When I updated it o `\n` It worked...

Before:
https://gitlab.com/viniciuspjardim/turborepo-test/-/jobs/1919408047

After:
https://gitlab.com/viniciuspjardim/turborepo-test/-/jobs/1919421580

### Weirdness

* Only `yarn.lock` was `\r\n`, all other files were `\n`
* Git should remove `\r` write? Maybe I messe with my config

**Comment by jaredpalmer** [comment]
This should be fixed in the latest canary thanks to #434

**Comment by NullVoxPopuli** [comment]
This is not resolved, :-\ 
```
❯ yarn list turbo
yarn list v1.22.17
└─ turbo@1.0.24-canary.0
Done in 3.89s.
```
```
❯ yarn turbo run start --scope="my-app" --include-dependencies
yarn run v1.22.17
$ <repo>/node_modules/.bin/turbo run start --scope=c2-cms-v2 --include-dependencies
 ERROR  yarn.lock: could not unmarshal lockfile: yaml: line 9712: could not find expected ':'}
```

Things have shifted around a bit, but line 9712 now is the same as in the original report.
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

I do not have `\r`:
```
❯ file -k yarn.lock
yarn.lock: ASCII text, with very long lines
```

**Comment by magalhas** [comment]
Facing the same problem on the latest version 1.0.28.

**Comment by NullVoxPopuli** [comment]
Just tried again, using └─ turbo@1.1.10

**Comment by productdevbook** [comment]
1.2.1 some problem

**Comment by florianmartens** [comment]
Experiencing the same. I dont think this issue should be closed.

**Comment by NullVoxPopuli** [comment]
I'd like to reopen this issue. @jaredpalmer  -- I still am running in to this and cannot adopt `turbo` with `yarn@v1` until this is resolved :cry: 

Using turbo 1.3.1.

can we use a different parser for the yarn.lock?
or somehow avoid needing to parse the yarn.lock?

**Comment by nathanhammond** [comment]
#948 is actually a duplicate of this but has the key detail of 1024 limit in go-yaml. As such I'm going to close this issue and we'll track the problem over there.
