### ISSUE TITLE
Searching docs is broken

### ISSUE THREAD

**Issue by six-transit** [vercel/turborepo#649]
### What version of Turborepo are you using?

n/a

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Other

### Describe the Bug

Search at https://turborepo.org/docs doesn't seem to work at the moment. Focusing/typing in the search box currently shows this in the console:

![image](https://user-images.githubusercontent.com/96151753/151894053-ec1288ea-df9e-40e7-8f20-434d6c873acd.png)

Hitting enter in the console shows this:

![image](https://user-images.githubusercontent.com/96151753/151894076-08dd0f4f-85f3-4c8a-b94d-70ca531112d4.png)

I see #615 raised this issue, but since it was closed I assume this was supposed to be fixed?

### Expected Behavior

Search should work!

### To Reproduce

Go to https://turborepo.org/docs and attempt to search

**Comment by jaredpalmer** [comment]
Fixed. Thanks!

**Comment by six-transit** [comment]
great! fwiw it's still not working for me -- i'm still seeing the same errors and can't search at all -- but maybe the fix isn't in the prod version of the docs yet?
